#!/bin/sh

# ./build-viewer $1

black .

git bumpmajor

git add --all . 

git commit -S -m 'feat!: day '"$1"' completed. Finally over all years!'

git push -u origin HEAD

gh pr create --fill --base main

gh pr merge --merge --auto